### ISSUE TITLE
Multiple Server Support

### ISSUE THREAD

**Issue by BroBeansCPG** [CreepPork/Apollo#130]
Firstly I’d just like to say thanks for the release! 

And also, I think adding support for monitoring multiple servers would be a useful feature.

**Comment by CreepPork** [comment]
Hi,

I must have missed the notification from you. I'd personally would like that feature too, but I think that it would just be easier to launch multiple instances of Apollo. If you would monitor multiple servers with the same bot, then you'd run into presentation issues. There are message length limits, badging wouldn't really work anymore in the sidebar and it would be awfully complex to make it work with multiple servers.

Let me know what you think.

**Comment by BroBeansCPG** [comment]
Completely fair enough, 

Yeah at the moment I just run 3 instances of the bot to stream all 3 servers. :) 

If it ain't broke don't fix it.
