### ISSUE TITLE
Feature Request: Player Count Notification

### ISSUE THREAD

**Issue by Radiumio** [CreepPork/Apollo#15]
_From eatpantboio on Discord:_
> I have a suggestion: Make a role that gets pinged whenever there are a significant amount of people on the public server (ex. 6 or more) Me and a few others would probably find that handy as constantly having to check #📄-public_server_info ends up being a bit annoying and I usually forget to do so

**Additional Suggestions**
- To prevent spam, there should be a cooldown between when the notifications happen, i.e. **40 minutes to an hour to prevent constant spam if the player count drops and rises rapidly.**
- To make a role joinable by members without bothering staff, we'll just supplement one of our current discord bots for an auto-role feature.

**Comment by CreepPork** [comment]
I think including role adding via reaction would be the best solution for all servers using Apollo to minimize them from running another bot.
